### ISSUE TITLE
希望添加个全屏下锁定/解锁 按钮

### ISSUE THREAD

**Issue by Huzhengtao** [abcd498936590/fijkplayer_skin#1]
不错的开箱即用插件，锁定解锁几乎是全屏必备的啦，希望可以添加哦

**Comment by abcd498936590** [comment]
有空会加下，之前这个就是凑合用，最近有空会更新下，修复下问题，然后播放列表看情况能不能加下。大概率就是这些了

**Comment by abcd498936590** [comment]
> 不错的开箱即用插件，锁定解锁几乎是全屏必备的啦，希望可以添加哦

最近两天我会更新一个重要版本，之前不跟手的快进快退，问题解决了，很顺畅，然后会加入播放列表，就是全屏之后，控制栏会多出一个选集，直接从播放器里面来选择哪一集。方便快捷。播放器UI部分的话，我会尽量看能不能加入锁定按钮或者其他的。可以期待一下

**Comment by Huzhengtao** [comment]
很nice啊 棒

**Comment by Huzhengtao** [comment]
对了，那个 官方那有个 [panel2皮肤](https://github.com/befovy/fijkplayer/blob/master/lib/ui/panel2.dart)。里面的面板左右区域调节亮度和声音挺不错的，可以结合一下，差不多就能是很好的皮肤了

**Comment by abcd498936590** [comment]
官方居然出皮肤了，我一会看看。等了他一年没出。给我憋坏了

**Comment by Huzhengtao** [comment]
哈哈，那个皮肤调节亮度和声音挺好，拖进度不好用

**Comment by abcd498936590** [comment]
> 哈哈，那个皮肤调节亮度和声音挺好，拖进度不好用

新版本已经发布，老兄可以看下，你要的锁定按钮，视频内播放列表切换，倍数切换，左右滑动快进快退，上下滑动音量屏幕亮度，全都有了。
目前就等fijkplayer作者修复偶发性播放器切换视频时候，状态不一致，目前基本完美皮肤
