### ISSUE TITLE
全屏的时候下面的进度条应该隐藏起来

### ISSUE THREAD

**Issue by leetomlee123** [abcd498936590/fijkplayer_skin#11]
![image](https://user-images.githubusercontent.com/19498940/140248800-02143668-7253-4661-86a6-c082502c8b3e.png)

**Comment by abcd498936590** [comment]
这属于萝卜青菜各有所爱了，这个地方不要的话可以传个参数config bottomPro = false，彻底不要这个贴底进度就行
