### ISSUE TITLE
建议：fijkplayer 升级到 0.9.0

### ISSUE THREAD

**Issue by cdk8s-zelda** [abcd498936590/fijkplayer_skin#2]
```
Because every version of fijkplayer_skin depends on fijkplayer ^0.8.7 and getx_demo depends on fijkplayer ^0.9.0, fijkplayer_skin is forbidden.
So, because getx_demo depends on fijkplayer_skin ^1.0.3, version solving failed.
```

**Comment by abcd498936590** [comment]
其实吧，fijkplayer就是版本变，别的没啥区别，你装个旧的就行了。然后准备最近有空更新下这个皮肤，之前是瞎写的，就是凑合能用，很烂。看时间吧

**Comment by abcd498936590** [comment]
> ```
> Because every version of fijkplayer_skin depends on fijkplayer ^0.8.7 and getx_demo depends on fijkplayer ^0.9.0, fijkplayer_skin is forbidden.
> So, because getx_demo depends on fijkplayer_skin ^1.0.3, version solving failed.
> ```

你试下0.8.7的，应该可以

**Comment by abcd498936590** [comment]
> ```
> Because every version of fijkplayer_skin depends on fijkplayer ^0.8.7 and getx_demo depends on fijkplayer ^0.9.0, fijkplayer_skin is forbidden.
> So, because getx_demo depends on fijkplayer_skin ^1.0.3, version solving failed.
> ```

最近两天我会更新一个重要版本，之前不跟手的快进快退，问题解决了，很顺畅，然后会加入播放列表，就是全屏之后，控制栏会多出一个选集，直接从播放器里面来选择哪一集。方便快捷。播放器UI部分的话，我会尽量看能不能加入锁定按钮或者其他的。可以期待一下

**Comment by cdk8s-zelda** [comment]
> > ```
> > Because every version of fijkplayer_skin depends on fijkplayer ^0.8.7 and getx_demo depends on fijkplayer ^0.9.0, fijkplayer_skin is forbidden.
> > So, because getx_demo depends on fijkplayer_skin ^1.0.3, version solving failed.
> > ```
> 
> 最近两天我会更新一个重要版本，之前不跟手的快进快退，问题解决了，很顺畅，然后会加入播放列表，就是全屏之后，控制栏会多出一个选集，直接从播放器里面来选择哪一集。方便快捷。播放器UI部分的话，我会尽量看能不能加入锁定按钮或者其他的。可以期待一下

我自己拷贝过去使用，发现确实有些问题。还有就是没有空安全。其实你不需要先加上那些左右拖动等功能。就先写好皮肤就行，比如改背景，改进度条等细节。功能如果想做就基于它的 fork 一个版本自己弄，或者提 pr。

**Comment by abcd498936590** [comment]
> > > ```
> > > Because every version of fijkplayer_skin depends on fijkplayer ^0.8.7 and getx_demo depends on fijkplayer ^0.9.0, fijkplayer_skin is forbidden.
> > > So, because getx_demo depends on fijkplayer_skin ^1.0.3, version solving failed.
> > > ```
> > 
> > 
> > 最近两天我会更新一个重要版本，之前不跟手的快进快退，问题解决了，很顺畅，然后会加入播放列表，就是全屏之后，控制栏会多出一个选集，直接从播放器里面来选择哪一集。方便快捷。播放器UI部分的话，我会尽量看能不能加入锁定按钮或者其他的。可以期待一下
> 
> 我自己拷贝过去使用，发现确实有些问题。还有就是没有空安全。其实你不需要先加上那些左右拖动等功能。就先写好皮肤就行，比如改背景，改进度条等细节。功能如果想做就基于它的 fork 一个版本自己弄，或者提 pr。

你要不使用fijkplayer做的面板2吧，他有一个测试面板有皮肤

**Comment by abcd498936590** [comment]
> > > ```
> > > Because every version of fijkplayer_skin depends on fijkplayer ^0.8.7 and getx_demo depends on fijkplayer ^0.9.0, fijkplayer_skin is forbidden.
> > > So, because getx_demo depends on fijkplayer_skin ^1.0.3, version solving failed.
> > > ```
> > 
> > 
> > 最近两天我会更新一个重要版本，之前不跟手的快进快退，问题解决了，很顺畅，然后会加入播放列表，就是全屏之后，控制栏会多出一个选集，直接从播放器里面来选择哪一集。方便快捷。播放器UI部分的话，我会尽量看能不能加入锁定按钮或者其他的。可以期待一下
> 
> 我自己拷贝过去使用，发现确实有些问题。还有就是没有空安全。其实你不需要先加上那些左右拖动等功能。就先写好皮肤就行，比如改背景，改进度条等细节。功能如果想做就基于它的 fork 一个版本自己弄，或者提 pr。

https://github.com/befovy/fijkplayer/blob/master/lib/ui/panel2.dart

**Comment by abcd498936590** [comment]
> ```
> Because every version of fijkplayer_skin depends on fijkplayer ^0.8.7 and getx_demo depends on fijkplayer ^0.9.0, fijkplayer_skin is forbidden.
> So, because getx_demo depends on fijkplayer_skin ^1.0.3, version solving failed.
> ```

如你所愿，已经升级到Flutter2.0，支持空安全，其他功能也一应俱全，详情可以查看md说明文件中有最新版本缩略图

新版本已经发布，老兄可以看下，你要的锁定按钮，视频内播放列表切换，倍数切换，左右滑动快进快退，上下滑动音量屏幕亮度，全都有了。
目前就等fijkplayer作者修复偶发性播放器切换视频时候，状态不一致，目前基本完美皮肤
