### ISSUE TITLE
flutter adk 版本问题

### ISSUE THREAD

**Issue by slhenryy** [abcd498936590/fijkplayer_skin#4]
客户端那边标明需要sdk 小于2.0.0
而这里你标明需要sdk需要支持空安全 就需要flutter的sdk 大于2.0.0

**Comment by abcd498936590** [comment]
> 客户端那边标明需要sdk 小于2.0.0
> 而这里你标明需要sdk需要支持空安全 就需要flutter的sdk 大于2.0.0

你只能是去fijkplayer仓库找旧版本的文件，然后找到皮肤的位置，自己修改了。因为fijkplayer也迁移到了支持空安全的版本，我也跟着迁移了
