### ISSUE TITLE
debug正常播放，flutter build apk后真机安装播放失败

### ISSUE THREAD

**Issue by msterzhang** [abcd498936590/fijkplayer_skin#7]
## 打包环境
```
D:\file\android\fijkplayer_skin\example>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.5.0, on Microsoft Windows [Version 10.0.17763.2237], locale zh-CN)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.5.5)
[√] Android Studio (version 4.1)
[√] IntelliJ IDEA Ultimate Edition (version 2018.3)
[√] Connected device (3 available)

! Doctor found issues in 1 category.
```

## 编译后的文件，麻烦老哥了

https://wwa.lanzoui.com/iM2ggvj37af

**Comment by abcd498936590** [comment]
你先把环境搞好吧。环境都不全

**Comment by abcd498936590** [comment]
> ## 打包环境
> ```
> D:\file\android\fijkplayer_skin\example>flutter doctor
> Doctor summary (to see all details, run flutter doctor -v):
> [√] Flutter (Channel stable, 2.5.0, on Microsoft Windows [Version 10.0.17763.2237], locale zh-CN)
> [!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
>     X cmdline-tools component is missing
>       Run `path/to/sdkmanager --install "cmdline-tools;latest"`
>       See https://developer.android.com/studio/command-line for more details.
>     X Android license status unknown.
>       Run `flutter doctor --android-licenses` to accept the SDK licenses.
>       See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
> [√] Chrome - develop for the web
> [√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.5.5)
> [√] Android Studio (version 4.1)
> [√] IntelliJ IDEA Ultimate Edition (version 2018.3)
> [√] Connected device (3 available)
> 
> ! Doctor found issues in 1 category.
> ```
> 
> ## 编译后的文件，麻烦老哥了
> https://wwa.lanzoui.com/iM2ggvj37af

你先把环境搞好吧。环境都不全

**Comment by msterzhang** [comment]
哈哈&nbsp; 我忘记改了，还以为你已经打包测试过😂



---原始邮件---
发件人: "KT ***@***.***&gt;
发送时间: 2021年10月19日(周二) 晚上7:01
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [abcd498936590/fijkplayer_skin] debug正常播放，flutter build apk后真机安装播放失败 (Issue #7)




  
环境弄好了，还是一个样子,的确还是有问题
 [√] Flutter (Channel stable, 2.5.0, on Microsoft Windows [Version 10.0.17763.2237], locale zh-CN) [√] Android toolchain - develop for Android devices (Android SDK version 31.0.0) [√] Chrome - develop for the web [√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.5.5) [√] Android Studio (version 2020.3)   
我刚看下下，你如果是用我的例子直接打包，那恭喜你，就是没给权限。我看了下我的例子的权限文件，确实正式打包，啥权限都没给。所以播放失败。你抄下我其他的flutter项目的权限。就可以了。这属于基础的知识。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
